class myfonts {
  static List val = [
    "Open Sans",
    "Roboto",
    "Poppins",
    "Lato",
    "Merriweather",
    "Montserrat",
    "Raleway",
    "Source Sans Pro",
    "Ubuntu",
    "Oswald",
    "Noto Sans",
    "Playfair Display",
    "PT Sans",
    "Avenir Next",
    "Helvetica Neue",
    "Source Serif Pro",
    "Quicksand",
    "Archivo Narrow",
    "Lora",
    "Inconsolata",
    "Arvo",
    "Abril Fatface",
    "Dosis",
    "Nunito",
    "Titillium Web",
    "Fira Sans",
    "Muli",
    "Varela Round",
    "Roboto Mono",
    "Philosopher",
    "Exo 2",
    "Bitter",
    "Cabin",
    "Play",
    "Work Sans",
    "Anton",
    "Slackey",
    "Vollkorn",
    "Ubuntu Condensed",
    "Crimson Text",
    "Pacifico",
    "ChunkFive",
    "PT Serif",
    "Lobster Two",
    "Yanone Kaffeesatz",
    "Open Sans Condensed",
    "Roboto Slab",
    "Cormorant Garamond",
    "Varela",
    "Staatliches",
    "Karla",
    "Libre Baskerville",
    "Bebas Neue",
    "PT Mono",
    "Hind Madurai",
    "Source Code Pro",
    "Rubik",
    "Goudy Bookletter 1911",
    "Monda",
    "Oswald Stencil",
    "Indie Flower",
    "Dancing Script",
    "Alice",
    "Kaushan Script",
    "Exo",
    "Josefin Sans",
    "Russo One",
    "Sacramento",
    "Lobster",
    "Dosis ExtraLight",
    "Cantarell",
    "Quicksand Light",
    "Poiret One",
    "Playfair Display SC",
    "Noto Serif",
    "Quattrocento Sans",
    "Ubuntu Mono derivative Powerline",
    "Roboto Condensed",
    "Anton Regular",
    "Pacifico Regular",
    "ChunkFive Regular",
    "PT Serif Caption",
    "Lobster Two Regular",
    "Yanone Kaffeesatz Regular",
    "Open Sans ExtraCondensed",
    "Roboto Slab Bold",
    "Cormorant Garamond Bold",
    "Arvo Bold",
    "Anton Bold",
    "Pacifico Bold",
    "ChunkFive Bold",
    "PT Serif Italic",
    "Lobster Two Italic",
    "Yanone Kaffeesatz Italic",
    "Open Sans Light",
    "Roboto Light",
    "Poppins Light",
    "Lato Light",
    "Merriweather Light",
    "Montserrat Light"
  ];
}
